---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
      - name: queue
        image: supinfo4kube/queue:1.0.1
        ports:
        - containerPort: 8161
        - containerPort: 61616

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
    - name: web
      port: 8161
      targetPort: 8161
    - name: broker
      port: 61616
      targetPort: 61616

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
      - name: position-simulator
        image: supinfo4kube/position-simulator:1.0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        ports:
          - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
      - name: position-tracker
        image: supinfo4kube/position-tracker:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: fleetman-position-tracker
  ports:
    - port: 30010 #! Naom -> 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
      - name: api-gateway
        image: supinfo4kube/api-gateway:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: fleetman-api-gateway
  ports:
    - port: 8080 #! Noam -> 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: webapp
        image: supinfo4kube/web-app:1.0.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
  ports:
    - port: 30080
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:3.6.23
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: fleetman-mongodb
  ports:
    - port: 27017
      targetPort: 27017