apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleetman-webapp
  name: fleetman-webapp
spec:
  type: NodePort
  ports:
    - port: 30080
      targetPort: 80
      nodePort: 30080
  selector:
    app: fleetman-webapp
