apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  type: ClusterIP
  ports:
    - name: "broker"
      port: 61616
      targetPort: 61616
    - name: "admin"
      port: 8161
      targetPort: 8161