apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleetman-webapp
  name: fleetman-webapp
spec:
  ports:
    - name: "30080"
      port: 30080
      targetPort: 80
  selector:
    app: fleetman-webapp
