apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleetman-position-tracker
  name: fleetman-position-tracker
spec:
  ports:
    - name: "30010"
      port: 30010
      targetPort: 8080
  selector:
    app: fleetman-position-tracker