apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleetman-api-gateway
  name: fleetman-api-gateway
spec:
  ports:
    - name: "30020"
      port: 30020
      targetPort: 8080
  selector:
    app: fleetman-api-gateway
